# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-14 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='incognito', max_length=20)),
                ('status', models.BooleanField(default=0)),
                ('permissions', models.IntegerField(default=2)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('text', models.CharField(max_length=1000)),
                ('time', models.CharField(default='error', max_length=8)),
                ('date', models.CharField(default='error', max_length=10)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='messenger.Users')),
            ],
            options={
                'db_table': 'Message',
            },
        ),
    ]
