# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-14 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_auto_20160914_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_notifications', models.BooleanField()),
                ('theme', models.CharField(default='light', max_length=5)),
                ('font_size', models.IntegerField(default=17)),
                ('two_step_verification', models.BooleanField(default=0)),
                ('logout_time', models.IntegerField(default=20)),
            ],
            options={
                'db_table': 'Settings',
            },
        ),
    ]
